language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'

matrix:
  allow_failures:
  - python: '3.7-dev'

sudo: false

git:
  depth: 1

install:
  - pip install --upgrade setuptools wheel
  - python setup.py sdist bdist_wheel
  - pip install dist/*.whl

script:
  - python -m unittest discover -v -s ya_speech_key/tests/

deploy:
  - provider: pypi
    username: "__token__"
    password:
      secure: "e0mR9PebKaIINSmxS6EqVpdC9K9mYE4zClCDnmM0YWUH0K9NMPHpI3V011C28WuiL86nWrVmfj3ilCSvPUy+rmC5Q0jBT2UN9p6QFUYir8LSeiA5DM0mkfOzslZXury2ZKyH8W4hN1MjoY3hZPhZXO38PeL67ZvL2SCC/9m/NJPGRFGagJAcj9GhTiyVp4COLCR4aaOoz4BqKQaAkppsqtuyl/+LPgyZyBACV465BkyT11MVkzb/rgiiiVG30BkQZECJtJb/mti6vwqxU0bc1ssocCGGjGV6kFykWC1yaQ1RZ+UZOaDGB9rPT+gd8BXB0maZoGT/D/hjFhTk0Eq7/07j8Lhf1AnlD5uLvdgynIc1gid761ktP6AMs/KC2wrI2CNj4pW3ZWWgqaeKyV1Nm6VuQvzV1rcoKd4JHGl18crNaCh/DmnIThsJSGkjKCTVJd7XWMGep7e4/93U64+VcdZL2GCzZMB/3fjsA0Y9+H/o4mUwHecWV4MiNXjjHvHqd13VcUswc2jP9BXC+LbcV1Y7W8nPCgDm3t/atSuBn2bwAa3ofHCEuTXt3+cpfqq4zaI8la4jrZY6F6BWbIoF7qp1tdO+W+CDNhJGHDv4IoxxVBP3/QRLhxQyamHRHj9VYKfS7x/Aeeq4LblqtcHTFRX1x4cv6zUJIC+kDRbRbVM="
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      condition: "$TRAVIS_PYTHON_VERSION == 3.6"
      tags: true
      branch: master

  - provider: pypi
    username: "__token__"
    password:
      secure: "e0mR9PebKaIINSmxS6EqVpdC9K9mYE4zClCDnmM0YWUH0K9NMPHpI3V011C28WuiL86nWrVmfj3ilCSvPUy+rmC5Q0jBT2UN9p6QFUYir8LSeiA5DM0mkfOzslZXury2ZKyH8W4hN1MjoY3hZPhZXO38PeL67ZvL2SCC/9m/NJPGRFGagJAcj9GhTiyVp4COLCR4aaOoz4BqKQaAkppsqtuyl/+LPgyZyBACV465BkyT11MVkzb/rgiiiVG30BkQZECJtJb/mti6vwqxU0bc1ssocCGGjGV6kFykWC1yaQ1RZ+UZOaDGB9rPT+gd8BXB0maZoGT/D/hjFhTk0Eq7/07j8Lhf1AnlD5uLvdgynIc1gid761ktP6AMs/KC2wrI2CNj4pW3ZWWgqaeKyV1Nm6VuQvzV1rcoKd4JHGl18crNaCh/DmnIThsJSGkjKCTVJd7XWMGep7e4/93U64+VcdZL2GCzZMB/3fjsA0Y9+H/o4mUwHecWV4MiNXjjHvHqd13VcUswc2jP9BXC+LbcV1Y7W8nPCgDm3t/atSuBn2bwAa3ofHCEuTXt3+cpfqq4zaI8la4jrZY6F6BWbIoF7qp1tdO+W+CDNhJGHDv4IoxxVBP3/QRLhxQyamHRHj9VYKfS7x/Aeeq4LblqtcHTFRX1x4cv6zUJIC+kDRbRbVM="
    distributions: bdist_wheel
    skip_existing: true
    on:
      condition: "$TRAVIS_PYTHON_VERSION == 2.7"
      tags: true
      branch: master
